command: ["python", "-u", "surge_dashboard_app.py"]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "DATABRICKS_TOKEN"
    valueFrom: "surge_model_endpoint"
  - name: "MODEL_ENDPOINT_NAME"
    value: "surge_multiplier_predictor"

resources:
  sql_warehouse:
    name: "Serverless Starter Warehouse"
    warehouse:
      id: "bda20b54525e3c76"
      permission: "CAN_USE"

  surge_model_endpoint:
    name: "surge_multiplier_predictor"
    serving_endpoint:
      name: "surge_multiplier_predictor"
      permission: "CAN_QUERY"
