command: ["python", "-u", "surge_dashboard_app.py"]
env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"

resources:
  sql_warehouse:
    name: "Serverless Starter Warehouse"
    warehouse:
      id: "bda20b54525e3c76"
      permission: "CAN_USE"

